CREATE TABLE IF NOT EXISTS tipos_ocorrencia (
  id INT AUTO_INCREMENT PRIMARY KEY,
  escola_id INT NOT NULL,
  motivo VARCHAR(255) NOT NULL,
  ativo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_motivo_escola (escola_id, motivo)
);
